### ISSUE TITLE
Request : General Notes - Tab View

### ISSUE THREAD

**Issue by arthem1990** [Rayquaza01/note-taker#5] opened 2017-11-22 08:52 UTC
It would be awesome if General Notes view was splitted into 4/5 horizontal tabs, and one could switch between them.
The concept of site notes is fine, but having everything in one place is another level.
Anyway, keep it up! Good job.

**Comment by Rayquaza01** [comment] 2018-06-29 02:15
Sorry for not getting to this sooner.

A tab strip has been added in the latest version (1.2.0) released today. It can be enabled by setting the "Number of Tabs" option to how many tabs you want. The tab strip appears on all types of notes (Domain, URL, and General), not just General Notes.

**Comment by mstar46** [comment] 2018-07-02 10:12
Hello to all!
I just installed note-taker and I have a few questions:
- even with an empty note there are two useless scroll bars; is that correct ?
- tab1 is empty when I open the window; to get the contents back I have to switch to tab2 and back,
- I can "Export Notes and Options" but the saved .json file (in Download folder, no choice!) contains only the options (the notes are lost!); do I miss something?
This add-on seems very useful... if I can make it work as it should!

**Comment by mstar46** [comment] 2018-07-10 05:41
I am a little disappointed not to receive help ...
After many tries I managed to display my three tabs in general mode. This is a partial answer to my second question, but new questions raise:
- "General notes" still doesn't work properly as default display; the display always returns to "URL notes", except for tab1 on opening
- many "words" (abbreviations, proper nouns ...) are underlined with red wavy lines: a dictionary is probably used by default; if so, can this be changed?
- scroll bars are always displayed, and I am still unable to export the notes with the options; and if I export a note using copy and paste in text mode the horizontal spacings are incorrect

**Comment by Rayquaza01** [comment] 2018-07-10 15:28
@mstar46  
Sorry about that. I haven't been able to reproduce the extra scroll bars in the popup or the export button only saving options. 

Your first new point is a bug. I'll put out an update to fix it soon.  
The red underline is Firefox's default spell check. You can right click a word and click "Add to Dictionary" to remove the underline from that word.  
On your last point, I can't reproduce copying the text from the popup with incorrect horizontal spacing.

What is your Firefox version and OS? Can you upload one of the exported options files? These might be helpful in reproducing the issues you're having.

Sorry, again, for not responding earlier.

**Comment by mstar46** [comment] 2018-07-11 02:09
Thanks for your quick answer.

- For the scroll bars I attach a screenshot of tab1 with just one word.
I just discovered that a second vertical scrollbar appears when you add sufficient lines to the text (tab2).
I attach two images (tab1 and tab2.jpg) because the popup disappears when I launch the screenshot tool.
- I attach an exported file notetaker.json and the corresponding storage.js
[notetaker.zip](https://github.com/Rayquaza01/note-taker/files/2182709/notetaker.zip)

- For the behaviour of the display of the "General Notes" I'll wait for the update.
- I tried the right-click to stop the spell-checking but nothing happens (no pull down menu). Here I can stop the spell-checking, change the language or add a dictionary without problem.
- I also attach a screenshot (tab3.jpg) with a note containing vertical aligned groups of words, and the same text copied to notepad.
![tab1](https://user-images.githubusercontent.com/40757121/42546382-e136c636-8508-11e8-8c95-038203acabc9.jpg)
![tab2](https://user-images.githubusercontent.com/40757121/42546393-f584c8e0-8508-11e8-898d-c2db100b2b44.jpg)
![tab3](https://user-images.githubusercontent.com/40757121/42546407-fe52f636-8508-11e8-894a-ba815f1428e5.jpg)
[tab3_copied.txt](https://github.com/Rayquaza01/note-taker/files/2182683/tab3_copied.txt)

- I just closed Firefox to let storage.js update before attaching it, and when I opened FF again all the notes were gone!

On my web site  http://maths.ac-noumea.nc/polyhedr/index_.htm
I use hundreds of Java animations and unfortunately most browsers don't support Java applets any longer; only Firefox ESR, MSIE (Windows) and Safari (Mac) still display them. That's why I presently use Firefox ESR 52.9.0 (32 bits) until the LiveGraphics3D applet will be translated from Java to JavaScript.
Do you suspect the version of Firefox? I use it on Win 7 and Win 10 and have the same behaviour.

**Comment by Rayquaza01** [comment] 2018-07-12 15:57
OK, so the extra scrollbars were apparently a bug with how [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Browser_compatibility) was handled. It's present on up to FF61. Essentially, the tabstrip and bottom buttons were taller than they should have been and added extra scrollbars.

The reason no context menu appears when you right click a word with red underline is because that was added after version 52. But judging by how many red underlines there are under real words, I think there may be something wrong with Firefox's dictionary. Installing a [new dictionary](https://addons.mozilla.org/en-US/firefox/language-tools/) might fix that issue.

Onto why the horizontal spacing changes when you copy it somewhere else. If you want to preserve horizontal spacing, you need to make sure that you use the same font settings in Notepad and Note Taker. Notepad uses a [monospaced font](https://en.wikipedia.org/wiki/Monospaced_font) by default, and Note Taker uses a proportional font by default. Setting both Notepad and Note Taker to the same font settings should fix the issue.

I still haven't been able to reproduce the notes not exporting with the options. Clearly, the notes are saving because it was in the attached storage.js. You can see the export code [here](https://github.com/Rayquaza01/note-taker/blob/5797460cd2f96fd41cbca793573a9d60e12cd949/extension/options.js#L112). It just stringifies the storage and sets it to a link. I don't really get how that can be broken for you, but not the rest of it.
Do you have storage issues with other webextensions? Does it happen in a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)/fresh install?

**Comment by mstar46** [comment] 2018-07-13 10:03
- scrollbars are ok
- spellcheck : I'll wait until the ESR branch updates to FF 53.
I'm French, thus my default dictionary is the French one... and I can't change it for the moment!
The installed dictionaries work all well when I fill a form.
- I missed to check the fonts in NotePad and Note Taker! But even with two identical proportional fonts it's not easy to preserve vertical alignments. I can live with that...
- More annoying: the export still missed the notes in a new profile. Strange... 
And more strange! now the export contains about 75% of the notes! (the last quarter is missing???)
No storage issues with other extensions.

**Comment by Rayquaza01** [comment] 2018-07-24 21:59
@mstar46 I'm not really sure why the problem would still be there in a new profile, or why it would only work for the first 75%. As a stopgap, I added a textbox on the options page that contains the raw JSON for the storage. I hope that it works for you.

Also, I'm sorry to be the bearer of bad news, but the next version of Firefox ESR is 60, not 53. According to the [ESR website](https://www.mozilla.org/en-US/firefox/organizations/), 52 ESR won't be supported after September 5, 2018.

**Comment by mstar46** [comment] 2018-07-27 10:05
@Rayquaza01
Strangely again now the export works well! why didn't it before? mysterious...
Concerning Firefox ESR you are right; I forgot that version 52 will be the  last which supports java plug-in. I hope that the javascript version of LiveGraphics3D will be soon available.
Thanks for sharing your nice work.

**Closed** 2018-09-07 14:39 UTC
Labels: enhancement
